
                            module.exports=['A R NAYANA', 'AAYUSHI' , 'ABHAY KATAL' , 'ABISHEK K RATHOD' , 'ADITHYA KASHYAP' 
                               , 'ADITI NYAMAGOUDAR' , 'AJAY' , 'AKASH' , 'AKHILA A' , 'AKSHAY N N' , 'AMAN AWASTHI'
                               , 'AMAR SHANKARAGOUDA PATIL' , 'ANANYA PALAIAH' , 'ANIKETH P'
                               , 'ANKIT NAHARIA', 'ANNAPPAGOUDA SHIVANGOUDA BIRADAR' , 'ARITRA ROY' , 'Ayan Paul'
                                 , 'B G SACHETH' , 'B GUNASHEELA' , 'B SHRINIDHI' , 'BASAVARAJ MAHALINGAPPA'
                              , 'BHADRINATH A NANDYAL' , 'BHARATH KUMAR' , 'BHUMIKA M' , 'BHUVAN KUMAR R H'
                                 , 'BOOMIKA K N' , 'CHANDRA KIRAN REDDY A' , 'CHINMAY J L' , 'CHIRAG K S'
                             , 'D M SHREEKANTH' , 'DARSHAN DIVAKAR KHANAPUR' , 'DARSHAN N' , 'DARSHAN REDDY D V'
                             , 'DARSHAN S' , 'DEEPAK GOWDA K' , 'DHANUSH S R' , 'DHANWANTH M' , 'DHEEMANT B P'
                             , 'GADIGE AKASH' , 'GAGAN B' , 'GAGAN DEEPAK V' , 'GAGAN GOWDA H P' , 'GAGAN R NAIK'
                             , 'GAGANA PRIYA C' , 'GAURAV M N' , 'GIRIDHAR R' , 'GOKUL RAJ K S' , 'H G SURYA'
                             , 'HARIKIRAN U S' , 'HARISH DILEEP' , 'HARISH RAJ C L' , 'HARSH DHANVANTH K GOWDA'
                             , 'HARSHAGOWDA P' , 'HEMANANDAN K' , 'HEMANG VISHRUT' , 'HEMANT THAKUR'
                             , 'HEMANTH KUMAR B' , 'HEMANTH R' , 'HITHESH N' , 'INDUMATI' , 'JEEVAN N'
                             , 'JEEVAN R GOWDA' , 'JINESH NAHTA' , 'JUTURU CHINNA RUTHWIK REDDY' , 'JAYARAM R'
                             , 'KARTHIK A NAIK' , 'KARTHIK M' , 'Kartik Hosamani' , 'KETAN PAVADSHETTY' , 'KHUSHI'
                             , 'KIFAYAT AMIN' , 'KIRAN' , 'KIRAN KUMAR N' , 'KRUPA S' , 'LEKHANA V'
                             , 'M HIMANSHU NARAYAN SAMRAJ' , 'M PAVAN KUMAR REDDY' , 'M SHALINI' , 'MAHADEV'
                             , 'MAHESH GANESH KOPPAD' , 'MALLAPPA' , 'MALLIKARJUN' , 'MALLIKARJUN GURULINGAPPA'
                             , 'MANJUNATHABABU LAKSHMAN NAIK' , 'MD ARSH PARVEZ' , 'MD FAZAL' , 'MEGHANA C S'
                             , 'MEGHASHREE R A' , 'MOHAMMED MUSTHAFA' , 'MOHAMMED SABEER' , 'MOHAN KUMAR H V'
                             , 'MOHAN PARTHA J' , 'Mohith Kotnada' , 'MUHAMMAD ZAIN HASAN V Y' , 'MYTHRI N'
                             , 'N S PRASANNA RAO' , 'NAFETH HUSSAIN S' , 'NAVEEN KUMAR S' , 'NEETHU P'
                             , 'NIKHIL KUMAR' , 'NIKHIL N KASHYAP' , 'NIKHIL VERMA' , 'Nisarga V' , 'OM TIWARI'
                             , 'P ARJUN G SHENOY' , 'PALLAVI U SHARMA' , 'PAVAN' , 'PAVAN B M' , 'PAVAN S REDDY'
                             , 'PAVITRA' , 'POLINA OMKAR GANESH' , 'PRADEEP S PATIL' , 'PRAFULLA KUMAR MISHRA'
                              , 'PRAJWAL' , 'PRAJWAL D M' , 'PRAJWAL N RAO' , 'PRANAY A KOTHARI' , 'PRATHAM RATLA P'
                             , 'PRATHUSHA B' , 'PRAVEEN KUMAR T S' , 'RAHUL T V' , 'RAJAT KUMAR' , 'Rakshit Baj'
                             , 'RAKSHITHA S' , 'RAM KUMAR R' , 'RANGASWAMY M Y' , 'RISHAV CHANDRA' , 'ROHAN B R'
                             , 'ROHAN CR' , 'ROHAN N R' , 'ROHAN S U' , 'ROHAN SAJJAN' , 'ROHIT SHIVOOR'
                             , 'ROHITH BASEPOGU' , 'ROSHAN JAMEER T M' , 'RUDRESH G S' , 'S SUMUKI' , 'SACHIN K N'
                             , 'SAIKIRAN S' , 'SAMRAT NAGARJUN R K' , 'SAMRIDDHI TIWARI' , 'SAMRUDH V A'
                             , 'SANDEEP H R' , 'SANDESH NAGORI' , 'SANGAMESH' , 'SANJAY R' , 'SHABARISH PATIL'
                             , 'SHANTAPPA' , 'SHARANA BASAVA' , 'SHARANAPPA RAMAPPA BHAJANTRI' , 'SHASHANK M'
                             , 'SHILPA KRISHNAPPA LAMANI' , 'SHIVSAI' , 'SHOIAB PASHA' , 'Shraddha H P'
                             , 'SHREYA.M D' , 'SHREYAS S' , 'SHUBHAM DEEP' , 'SHUBHAM KUMAR' , 'SINCHANA N SHETTY'
                             , 'SINDHUJA Y S' , 'SNEHA BORAH' , 'SNEHA PAI' , 'SOHAM GOWDA N' , 'SPANDANA'
                             , 'SREE KIRAN B S' , 'SRI RAM SHARMA', 'SRUJAN G' , 'SUDEEP M HAVERI' , 'SUHAS A S'
                             , 'SUSHMA' , 'TANMAY KANKARIYA' , 'TEJAS KUMAR N' , 'TEJAS REDDY V' , 'TEJASHREE R'
                             , 'TEJU K R' , 'TUSHAR LAKHOTIA' , 'UBEDHUSAIN SHAFIAHAMED' , 'UDIPTHA J'
                             , 'UMANG SINGH' , 'A VAMSHI KRISHNA' , 'VIDYA SURESH SHIVAPPANAVAR' , 'VIKAS R'
                             , 'VINAY M' , 'VISHRUTH K REDDY' , 'VISHWAS VINAYAK HULLUR' , 'VISMITHA R'
                             , 'YASHAS CHANDRA H M' , 'YASHPALKUMAR C S' , 'ZEESHAN MOHAMMED' , 'ANIL KUMAR SAH'
                             , 'BISHAL BHURTEL' , 'MANISH DAS' , 'OM BIKRAMTHAPA' , 'PALLAVI ACHARYA' , 'SANTOSH'
                              , 'SHRAWAN KUMAR YADAV' , 'SULIMAN RAHIMI' ]; 





                             